defaults:
  - _self_
  - model: vqvae
  - task: vqvae
  - data: medmnist3d
  - optimizer: adam
  - trainer: default
  - callbacks: vqvae
  - optional scheduler: cosine
  - optional logger: tensorboard

seed: 42
checkpoint_path: null